### ISSUE TITLE
Styles at the bottom

### ISSUE THREAD

**Issue by csswizardry** [mxstbr/personal-website#3]
You’re linking to your CSS at [the bottom of your document](https://github.com/mxstbr/personal-website/blob/bc01e6016297ad7beca00c3a40ebf8ce541cb67b/components/_footer.html#L12-L14), which is a pretty big performance no-no (delayed CSSOM construction and FOUC).

I’m not sure if there’s a reason for doing this (there doesn’t appear to be a JS dependency or similar), but if not then I would move them to as close to the top of your HTML as possible :)

**Comment by mxstbr** [comment]
Thanks for the audit, PR very welcome!
